### ISSUE TITLE
SnpArray as input for SModel

### ISSUE THREAD

**Issue by crsl4** [joshday/SparseRegression.jl#15] opened 2017-10-23 18:20 UTC
It would be great if we could use a `SnpArray` object as input for an `SModel`, instead of having to convert to a matrix which can be very heavy: @klkeys @Hua-Zhou
```julia
using DataFrames, SparseRegression, SnpArrays, Distributions
chr = SnpArray("SNP_data29a_missing"; people = 212, snps = 253141)
typeof(chr) #SnpArrays.SnpArray{2}
SnpArray <: AbstractArray #true
y = convert(Vector{Float64},randn(212).>0)
y[y.==0] = -1 # SparseRegression needs outcome -1,1
isa(chr,AbstractArray) #true
s = SModel(chr,y, LogitDistLoss(), L1Penalty())
@time learn!(s)
## ERROR: MethodError: no method matching *(::Tuple{Bool,Bool}, ::Float64)
```
So, the multiplication operations does not work properly. It would be great if they did, as we would avoid converting a big dataset to float matrix. This requires a lot of work, so it is only a suggestion of something that would be cool to have in `SparseRegression`, thanks!

**Comment by crsl4** [comment] 2017-10-23 18:44
This seems to be related to a previous issue in `SnpArrays`, see [here](https://github.com/OpenMendel/SnpArrays.jl/issues/2)

**Comment by joshday** [comment] 2017-10-24 02:35
I'll close this since the issue is in SnpArrays, but I'll add a note in the docs how the `x` matrix requires methods for A_mul_B! and At_mul_B!

**Closed by joshday** 2017-10-24 02:35 UTC

**Comment by joshday** [comment] 2017-10-24 02:44
NOTE: This is absolutely terrible, but should get the code working (untested)

```julia
Base.A_mul_B!(x::Matrix{Float64}, a::SnpArray, b::Vector{Float64}) = (x[:] = a * b)
Base.At_mul_B!(x::Matrix{Float64}, a::SnpArray, b::Vector{Float64}) = (x[:] = x'b)
```

**Comment by crsl4** [comment] 2017-10-24 16:10
Thanks Josh! I will give it a try:)

**Comment by crsl4** [comment] 2017-10-24 19:58
No, I still get the same error. I will keep exploring, thanks

**Comment by joshday** [comment] 2017-10-24 20:01
Ah, sorry.  I thought SnpArray had methods for `*` but I guess it doesn't, so it lands on the fallback definition using getindex:

https://github.com/OpenMendel/SnpArrays.jl/blob/d878a31b7ef9d118f3113da2ac1bc1f14b0a98e4/src/SnpArrays.jl#L108-L110
